{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kiss-eck.name" . }}-kibana
  labels:
  {{- include "kiss-eck.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.kibanaDomain }}
    http:
      paths:
      - backend:
          service:
            name: kiss-kb-http
            port:
              number: 5601
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.kibanaDomain }}
    secretName: wildcard-kiss-tls
{{- end }}